import React,{useEffect,useMemo,useState}from'react'
import{createRoot}from'react-dom/client'
import{Home,BookOpen,Images,WalletCards,StickyNote,Plus,Heart,Trash2,LogOut,Cloud,Copy,Upload,CheckCircle2}from'lucide-react'
import{supabase,ready}from'./supabaseClient'
import'./styles.css'
const BUCKET='between-us-photos'
const fmt=d=>d?new Date(d).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'刚刚'
const code=()=>Math.floor(100000+Math.random()*900000).toString()

function App(){
 const[session,setSession]=useState(null),[space,setSpace]=useState(null),[tab,setTab]=useState('home'),[msg,setMsg]=useState(''),[modal,setModal]=useState(''),[data,setData]=useState({records:[],albums:[],expenses:[],memos:[]}),[loading,setLoading]=useState(true)
 useEffect(()=>{if(!ready){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data:l}=supabase.auth.onAuthStateChange((_,s)=>{setSession(s);if(!s){setSpace(null);setData({records:[],albums:[],expenses:[],memos:[]})}});return()=>l.subscription.unsubscribe()},[])
 useEffect(()=>{if(session?.user)loadSpace()},[session?.user?.id])
 async function loadSpace(){const{data,error}=await supabase.from('couple_members').select('space_id,couple_spaces(id,name,invite_code)').eq('user_id',session.user.id).limit(1);if(error){setMsg(error.message);return}const s=data?.[0]?.couple_spaces||null;setSpace(s);if(s)loadData(s.id)}
 async function loadData(id=space?.id){if(!id)return;const [r,a,e,m]=await Promise.all(['records','albums','expenses','memos'].map(t=>supabase.from(t).select('*').eq('space_id',id).order('created_at',{ascending:false})));const er=r.error||a.error||e.error||m.error;if(er){setMsg(er.message);return}setData({records:r.data||[],albums:a.data||[],expenses:e.data||[],memos:m.data||[]})}
 async function createSpace(name){const{data:s,error}=await supabase.from('couple_spaces').insert({name:name||'Between Us',invite_code:code(),created_by:session.user.id}).select().single();if(error){setMsg(error.message);return}const{error:me}=await supabase.from('couple_members').insert({space_id:s.id,user_id:session.user.id,role:'owner'});if(me){setMsg(me.message);return}setSpace(s);loadData(s.id)}
 async function joinSpace(c){const{data:s,error}=await supabase.from('couple_spaces').select('*').eq('invite_code',c.trim()).single();if(error){setMsg('没有找到这个绑定码');return}const{error:je}=await supabase.from('couple_members').insert({space_id:s.id,user_id:session.user.id,role:'member'});if(je&&!je.message.includes('duplicate')){setMsg(je.message);return}setSpace(s);loadData(s.id)}
 async function upload(file){if(!file)return'';const ext=file.name.split('.').pop()||'jpg',path=`${space.id}/${Date.now()}.${ext}`;const{error}=await supabase.storage.from(BUCKET).upload(path,file);if(error)throw error;return supabase.storage.from(BUCKET).getPublicUrl(path).data.publicUrl}
 async function add(table,row,file){try{const image_url=file?await upload(file):row.image_url;const{error}=await supabase.from(table).insert({...row,image_url,space_id:space.id,user_id:session.user.id,author_name:session.user.email?.split('@')[0]||'Me'});if(error)throw error;setModal('');loadData()}catch(e){setMsg(e.message)}}
 async function del(table,id){const{error}=await supabase.from(table).delete().eq('id',id);error?setMsg(error.message):loadData()}
 async function like(x){await supabase.from('records').update({likes:(x.likes||0)+1}).eq('id',x.id);loadData()}
 async function toggle(x){await supabase.from('memos').update({done:!x.done}).eq('id',x.id);loadData()}
 const spent=data.expenses.reduce((s,x)=>s+Number(x.amount||0),0),pct=Math.min(100,Math.round(spent/3000*100))
 if(loading)return <Shell><Center text="正在连接云端..."/></Shell>
 if(!ready)return <Shell><Center text="缺少 .env.local 配置"/></Shell>
 if(!session)return <Shell><Auth msg={msg} setMsg={setMsg}/></Shell>
 if(!space)return <Shell><Space email={session.user.email} msg={msg} createSpace={createSpace} joinSpace={joinSpace}/></Shell>
 return <Shell><header><button onClick={()=>loadData()}>同步</button><b>Between Us</b><button onClick={()=>supabase.auth.signOut()}><LogOut size={17}/></button></header>{msg&&<p className="msg">{msg}<button onClick={()=>setMsg('')}>×</button></p>}<main>{tab==='home'&&<HomePage space={space} data={data} spent={spent} pct={pct}/>} {tab==='record'&&<Records data={data.records} del={del} like={like}/>} {tab==='album'&&<Albums data={data.albums} del={del}/>} {tab==='budget'&&<Budget data={data.expenses} spent={spent} pct={pct} del={del}/>} {tab==='memos'&&<Memos data={data.memos} del={del} toggle={toggle}/>}</main><button className="fab" onClick={()=>setModal(tab==='album'?'album':tab==='budget'?'expense':tab==='memos'?'memo':'record')}><Plus/></button><nav>{[['home',Home],['record',BookOpen],['album',Images],['budget',WalletCards],['memos',StickyNote]].map(([id,Icon])=><button key={id} className={tab===id?'on':''} onClick={()=>setTab(id)}><Icon size={20}/><span>{id}</span></button>)}</nav>{modal&&<Modal title="新增" close={()=>setModal('')}>{modal==='record'&&<RecordForm onSubmit={(r,f)=>add('records',r,f)}/>} {modal==='album'&&<AlbumForm onSubmit={(r,f)=>add('albums',r,f)}/>} {modal==='expense'&&<ExpenseForm onSubmit={r=>add('expenses',r)}/>} {modal==='memo'&&<MemoForm onSubmit={r=>add('memos',r)}/>}</Modal>}</Shell>
}
function Shell(p){return <div className="app"><div className="phone">{p.children}</div></div>}
function Center({text}){return <div className="center"><Cloud/><h2>{text}</h2></div>}
function Auth({msg,setMsg}){const[mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState('');async function sub(e){e.preventDefault();setMsg('');const res=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(res.error)setMsg(res.error.message)}return <div className="auth"><h1>Between Us</h1><p>登录后即可云同步。</p>{msg&&<p className="msg">{msg}</p>}<form onSubmit={sub}><input type="email" placeholder="邮箱" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="密码至少 6 位" minLength="6" value={password} onChange={e=>setPassword(e.target.value)} required/><button>{mode==='login'?'登录':'注册'}</button></form><button className="link" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'去注册':'去登录'}</button></div>}
function Space({email,msg,createSpace,joinSpace}){const[name,setName]=useState('Between Us'),[c,setC]=useState('');return <div className="auth"><h1>情侣空间</h1><p>{email}</p>{msg&&<p className="msg">{msg}</p>}<section><h3>创建空间</h3><input value={name} onChange={e=>setName(e.target.value)}/><button onClick={()=>createSpace(name)}>创建</button></section><section><h3>加入空间</h3><input placeholder="6 位绑定码" maxLength="6" value={c} onChange={e=>setC(e.target.value)}/><button onClick={()=>joinSpace(c)}>加入</button></section></div>}
function HomePage({space,data,spent,pct}){return <div className="page"><section className="hero"><div><p>云同步已开启</p><h1>{space.name}</h1><button className="code" onClick={()=>navigator.clipboard.writeText(space.invite_code)}>{space.invite_code}<Copy size={16}/></button><p>把这个绑定码给对方。</p></div><Cloud size={46}/></section><div className="grid"><Card n={data.records.length} t="记录"/><Card n={data.albums.length} t="照片"/><Card n={`¥${3000-spent}`} t="剩余"/><Card n={data.memos.filter(x=>!x.done).length} t="待办"/></div><section><h3>预算</h3><p>已用 ¥{spent} / ¥3000</p><div className="bar"><i style={{width:pct+'%'}}/></div></section></div>}
function Card({n,t}){return <section className="card"><b>{n}</b><span>{t}</span></section>}
function Records({data,del,like}){return <div className="page"><Title t="Record"/>{data.map(x=><section className="item" key={x.id}><b>{x.author_name}</b><small>{fmt(x.created_at)} · {x.tag}</small><p>{x.text}</p>{x.image_url&&<img src={x.image_url}/>}<div><button onClick={()=>like(x)}><Heart size={16}/>{x.likes||0}</button><button onClick={()=>del('records',x.id)}><Trash2 size={16}/></button></div></section>)}</div>}
function Albums({data,del}){return <div className="page"><Title t="Album"/><div className="photos">{data.map(x=><section key={x.id}><img src={x.image_url}/><b>{x.title}</b><p>{x.note}</p><button onClick={()=>del('albums',x.id)}><Trash2 size={16}/></button></section>)}</div></div>}
function Budget({data,spent,pct,del}){return <div className="page"><Title t="Budget"/><section className="budget"><p>本月已用</p><h2>¥{spent}</h2><div className="bar"><i style={{width:pct+'%'}}/></div></section>{data.map(x=><section className="row" key={x.id}><div><b>{x.title}</b><small>{x.category} · {fmt(x.created_at)}</small></div><strong>¥{x.amount}</strong><button onClick={()=>del('expenses',x.id)}><Trash2 size={16}/></button></section>)}</div>}
function Memos({data,del,toggle}){return <div className="page"><Title t="Memos"/>{data.map(x=><section className={'row '+(x.done?'done':'')} key={x.id}><button onClick={()=>toggle(x)}><CheckCircle2 size={20}/></button><div><b>{x.title}</b><small>{x.type}{x.remind?' · '+x.remind:''}</small></div><button onClick={()=>del('memos',x.id)}><Trash2 size={16}/></button></section>)}</div>}
function Title({t}){return <h2 className="title">{t}</h2>}
function Modal({children,close,title}){return <div className="sheet"><div><header><b>{title}</b><button onClick={close}>×</button></header>{children}</div></div>}
function File({setFile}){return <label className="file"><Upload size={16}/>选择图片<input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>}
function RecordForm({onSubmit}){const[text,setText]=useState(''),[tag,setTag]=useState('日常'),[file,setFile]=useState(null);return <form onSubmit={e=>{e.preventDefault();onSubmit({text,tag},file)}}><textarea required placeholder="写下这一刻" value={text} onChange={e=>setText(e.target.value)}/><select value={tag} onChange={e=>setTag(e.target.value)}><option>日常</option><option>约会</option><option>计划</option></select><File setFile={setFile}/><button>发布</button></form>}
function AlbumForm({onSubmit}){const[title,setTitle]=useState(''),[note,setNote]=useState(''),[file,setFile]=useState(null);return <form onSubmit={e=>{e.preventDefault();onSubmit({title,note},file)}}><input required placeholder="标题" value={title} onChange={e=>setTitle(e.target.value)}/><input placeholder="备注" value={note} onChange={e=>setNote(e.target.value)}/><File setFile={setFile}/><button>上传</button></form>}
function ExpenseForm({onSubmit}){const[title,setTitle]=useState(''),[amount,setAmount]=useState(''),[category,setCategory]=useState('约会');return <form onSubmit={e=>{e.preventDefault();onSubmit({title,amount,category})}}><input required placeholder="支出名称" value={title} onChange={e=>setTitle(e.target.value)}/><input required type="number" placeholder="金额" value={amount} onChange={e=>setAmount(e.target.value)}/><select value={category} onChange={e=>setCategory(e.target.value)}><option>约会</option><option>旅行</option><option>礼物</option><option>生活</option></select><button>添加</button></form>}
function MemoForm({onSubmit}){const[title,setTitle]=useState(''),[type,setType]=useState('待办'),[remind,setRemind]=useState('');return <form onSubmit={e=>{e.preventDefault();onSubmit({title,type,remind})}}><input required placeholder="备忘内容" value={title} onChange={e=>setTitle(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value)}><option>待办</option><option>惊喜</option><option>灵感</option></select><input placeholder="提醒时间" value={remind} onChange={e=>setRemind(e.target.value)}/><button>保存</button></form>}
createRoot(document.getElementById('root')).render(<App/>)
